# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('comment', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('password', models.CharField(default='123456', max_length=32)),
            ],
        ),
    ]
